gText_Birch_Welcome::
        .string "¡Hola! ¡Perdón por hacerte esperar!\p"
        .string "¡Bienvenido al mundo de los POKéMON!\p"
        .string "Mi nombre es BIRCH.\p"
        .string "Pero todos me llaman el PROFESOR\n"
        .string "POKéMON.\p"
        .string "$"

gText_Birch_Pokemon::
        .string "Esto es lo que llamamos un “POKéMON”.\p"
        .string "\n"
        .string "$"

gText_Birch_MainSpeech::
        .string "Este mundo está ampliamente habitado\n"
        .string "por muchos tipos de POKéMON.\p"
        .string "Los humanos convivimos con ellos,\n"
        .string "a veces como amigos y compañeros,\l"
        .string "y otras como compañeros de trabajo.\p"
        .string "Y en ocasiones nos unimos para\n"
        .string "combatir contra otros.\p"
        .string "Pero a pesar de nuestra cercanía, no\n"
        .string "lo sabemos todo sobre los POKéMON.\p"
        .string "De hecho, existen muchos, muchos\n"
        .string "misterios que rodean a los POKéMON.\p"
        .string "Para desentrañar estos misterios, he\n"
        .string "dedicado mi vida a la investigación.\l"
        .string "Eso es a lo que me dedico.\p"
        .string "$"

gText_Birch_AndYouAre::
        .string "¿Y tú quién eres?$"

gText_Birch_BoyOrGirl::
        .string "¿Eres un chico?\n"
        .string "¿O eres una chica?$"

gText_Birch_WhatsYourName::
        .string "Muy bien.\n"
        .string "¿Cómo te llamas?$"

gText_Birch_SoItsPlayer::
        .string "Así que eres {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
        .string "¡Ah, ya veo!\p"
        .string "Así que eres {PLAYER}{KUN} y te mudas\n"
        .string "a mi pueblo natal, PUEBLO RAÍZ.\l"
        .string "¡Ahora lo entiendo!\p"
        .string "$"

gText_Birch_AreYouReady::
        .string "Muy bien, ¿estás listo?\p"
        .string "Tu propia aventura está a punto de\n"
        .string "comenzar.\p"
        .string "Reúne valor y adéntrate en el mundo\n"
        .string "de los POKéMON, donde te esperan\l"
        .string "sueños, aventuras y amistades.\p"
        .string "Bien, te estaré esperando.\n"
        .string "Ven a verme a mi LABORATORIO POKéMON.\p"
        .string "$"
