OldaleTown_House1_MapScripts::
	.byte 0

OldaleTown_House1_EventScript_Woman::
	msgbox OldaleTown_House1_Text_LeftPokemonGoesOutFirst, MSGBOX_NPC
	end

OldaleTown_House1_Text_LeftPokemonGoesOutFirst:
        .string "Al combatir, el POKéMON que esté el\n"
        .string "primero de la lista saldrá primero.\p"
        .string "Así que, cuando tengas más POKéMON,\n"
        .string "prueba a cambiar el orden de tu\l"
        .string "equipo.\p"
        .string "Podría darte una gran ventaja.$"

